import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Header } from "@/components/Header/Header";
import { Contact } from "@/components/Contact/Contact";
import { Footer } from "@/components/Footer/Footer";
import { Tree } from "@/components/Tree/Tree";
import { TreeNavigation } from "@/components/TreeNavigation/TreeNavigation";
import { useState, useRef } from "react";

export default function Home() {
  const [chosenCategory, setChosenCategory] = useState(null);
  const treeRef = useRef(null);

  const handleClick = (value) => {
    setChosenCategory(value);
    // scrollToTree();
  };
  console.log(chosenCategory);

  const handleBack = () => {
    setChosenCategory(null);
  };

  // const scrollToTree = () => {
  //   if (treeRef.current) {
  //     treeRef.current.scrollIntoView({ behavior: "smooth" });
  //   }
  // };

  return (
    <>
      <Header></Header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {chosenCategory !== null && <button onClick={handleBack}>zpět</button>}
        {chosenCategory === null && <TreeNavigation onClick={handleClick} />}
      </main>
      <div ref={treeRef}>
        <Tree category={chosenCategory} />
      </div>
      <Footer />
    </>
  );
}
