import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { Header } from '@/components/Header/Header';
import { Contact } from '@/components/Contact/Contact';
import { Footer } from '@/components/Footer/Footer';

export default function Home() {
  return (
    <>
      <Header></Header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Contact />
      </main>
      <Footer />
    </>
  );
}
