// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      id: 0,
      target: 'První uvolnění',
      targetId: 'stabilization',
      nameOfRelaxation: 'Základní dechové cvičení pro získání klidu',
      keyWords: 'Dýchej',
      typeOfRelaxation: 'Dechové cvičení',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Lehce se dotkni rtů a trochu pootevři pusu.',
          'Nadechni se nosem a počítej do tří.',
          'Vydechuj a počítej do šesti, zopakuj třikrát.',
          'Teď měj výdech stejně dlouhý jako nádech (třeba nádech na čtyři a výdech na čtyři) a pokračuj tak jednu minutu.',
          'Polož si ruku na břicho a snaž se ho s každým nádechem zvednout.',
        ],
        audio: '',
      },
    },
    {
      id: 1,
      target: 'První uvolnění',
      targetId: 'stabilization',
      nameOfRelaxation: 'Základní progresivní svalová relaxace',
      keyWords: 'Zatni ruce v pěst a uvolni',
      typeOfRelaxation: 'Progresivně svalová relaxace',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Zatni jednu svou ruku v pěst co nejpevněji.',
          'Až bude stisk co nejsilnější, uvolni ho.',
          'Nadechni se a vydechni.',
          'To samé zopakuj s druhou rukou.',
          'Nadechni se a vydechni.',
          'Spolu s uvolněním odchází z těla to nejhorší napětí.',
          'Opakuj dokud se stav nejhoršího napětí nezlepší.',
        ],
        audio: '',
      },
    },
    {
      id: 2,
      target: 'První uvolnění',
      targetId: 'stabilization',
      nameOfRelaxation: 'Tipy na to, jak aktuálně zpomalit',
      keyWords: 'Zpomal svůj pohyb',
      typeOfRelaxation: 'Mindfullness',
      formOfRelaxation: 'Audionahrávka',
      content: {
        text: '',
        audio: 'Zpomal.mp3',
      },
    },
    {
      id: 3,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOfRelaxation: 'Jak tu být sám pro sebe',
      keyWords: 'Buď sám pro sebe',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Vzpomeň si, nebo si zkus představit, jaké to je, když tu pro někoho jsi.',
          'Pro kámoše/kámošku, mladšího sourozence, někoho v nouzi, nebo domácího mazlíčka.',
          'Všímej si svých pocitů, můžeš cítit: zájem, věrnost, obhajování, rozhodnost.',
          'Teď si vzpomeň, jaké to bylo když jsi byl/a úplně malé dítě.',
          'Bezbranné, roztomilé.',
          'Zkus vyjádřit ochranu a starost o tohle malé dítě.',
          'Zkus se obejmout tak pevně, jako bys objímal/a toto dítě.',
          'Všímej si jak se cítíš, když jsi na své straně.',
          'Pokud ti něco brání v tomhle pocitu, zkus to na chvíli nechat být.',
          'Nemůže tě to ohrozit.',
          'Jsi tu jen pro sebe.',
          'Nakonec se zeptej sám/sama sebe: Pokud jsem na své straně, co bude nejlepší udělat?',
        ],
        audio: '',
      },
    },
    {
      id: 4,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOfRelaxation: 'Arteterapeutický superhrdina (kresba, psaní)',
      keyWords: 'Tvoř svého superhrdinu',
      typeOfRelaxation: 'Arteterapie',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Zkus si vymyslet vlastního superhrdinu, který by tvoje problémy vyřešil levou zadní.',
          'Můžeš o něm psát, nebo ho nakreslit.',
          'Dej mu jméno, vymysli, jestli to bude člověk, zvíře, duch, nebo tvor z jiné planety.',
          'Jestli píšeš, popiš, jaké vlastnosti a superschopnosti by měl mít, aby tvůj problém vyřešil.',
          'Pokud kreslíš, zobraz části těla, zbraně nebo jiné nástroje, které by mu pomohly problém vyřešit.',
        ],
        audio: '',
      },
    },
    {
      id: 5,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOfRelaxation: 'Imaginace pro navození pocitu sebelásky a soucitu',
      keyWords: 'Zažij soucit',
      typeOfRelaxation: 'Imaginace a vizualizace',
      formOfRelaxation: 'Audionahrávka',
      content: {
        text: '',
        audio: 'Zazij_soucit.mp3',
      },
    },
    {
      id: 6,
      target: 'řešení problému, změna, vlastní aktivita',
      targetId: 'problemsolving',
      nameOfRelaxation: 'Tipy k asertivní a respektující komunikaci',
      keyWords: 'Řešení promluvou',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Bez znalosti situace ti nedáme přesný návod na rozhovor.',
          'Ale máme pár tipů pro komunikaci s ostatními:',
          'Pamatuj, že máš stejné práva, názory, potřeby a sny jako kdokoliv jiný.',
          'Máš právo, aby s tebou lidé jednali dobře. I ostatní mají toto právo.',
          'Buď upřímný/á k sobě i ostatním.',
          'Na rozhovor se připrav a ujasni si, co potřebuješ.',
          'Nehodnoť ostatní. Řekni konkrétně, co ti vadí.',
          'Nabídni řešení, co tě napadají, a poslouchej řešení druhé strany.',
          'Možná budeš muset udělat kompromis.',
          'Dohoda musí být přijatelná pro obě strany, jinak to není dohoda.',
          'Nemusíš pokračovat v rozhovoru s naštvaným člověkem, můžeš ho odložit.',
          'Manipulace do respektujícího rozhovoru nepatří, nauč se ji rozeznat.',
          'Neboj se požádat o pomoc.',
        ],
        audio: '',
      },
    },
    {
      id: 7,
      target: 'řešení problému, změna, vlastní aktivita',
      targetId: 'problemsolving',
      nameOfRelaxation: 'Jak se někomu svěřit',
      keyWords: 'Svěř se',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Nikdy na nic nemusíš být sám.',
          'Nejlepší je svěřit se někomu, když cítíš, že problém sám nezvládneš.',
          'Nejedná se o žalování, pokud jsi v situaci bezradný/á.',
          'Mohou ti pomoci rodiče, blízký příbuzný, kamarád, učitel, školní psycholog, zaměstnanec školy, vedoucí kroužku, trenér.',
          'Pokud pomoc někoho známého nezabere, neboj se zkusit to u někoho jiného.',
          'Existuje také pomoc zvenčí, jako centrum Locika nebo Linka bezpečí, takovou pomoc později najdeš v našich kontaktech.',
        ],
        audio: '',
      },
    },
    {
      id: 8,
      target: 'řešení problému, změna, vlastní aktivita',
      targetId: 'problemsolving',
      nameOfRelaxation: 'Co dělat, když nevidím řešení',
      keyWords: 'Tohle řešit nejde',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Být tu sám pro sebe znamená, že ti na sobě záleží.',
          'Znamená to, že chceš být šťastný/á, ne ustaraný/á, smutný/á, naštvaný/á, nebo provinilý/á.',
          'To, jak se aktuálně cítíš, je důležité nejen teď, ale i pro tvoje budoucí já, které bude čerpat i z této zkušenosti.',
          'Pokud jsi došel/došla až sem, udělal/a jsi pro sebe zásadní krok.',
          'Znamená to, že jsi získal/a odvahu a rozhodl/a ses pro řešení své situace, i když ho teď třeba nevidíš.',
          'Můžeš vyzkoušet i jiná cvičení z MindSprout.',
          'Nebo daná situace může vyžadovat víc času než jedno rychlé řešení.',
          'Pokud cítíš, že ti MindSprout nepomůže, můžeš vyzkoušet odkazy na konci stránky.',
        ],
        audio: '',
      },
    },
    {
      id: 9,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOfRelaxation: 'Jak se smířit s omezením svého vlivu',
      keyWords: 'Ne vše lze vždy ovlivnit',
      typeOfRelaxation: 'Imaginace a vizualizace',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Když se něco změní tak, že to nemůžeš vrátit zpět, bývá nejtěžší to přijmout.',
          'Něco se rozbilo, jsi smutný/á a neumíš se rozveselit, stojíš ve frontě.',
          'Zeptej se sebe: Můžu přijmout, že to tak je, ať už se mi to líbí nebo ne?',
          'To neznamená souhlas, přehlížení, odpuštění nebo podvolení se. Prostě to jenom teď nemůžeš ovlivnit.',
          'Pokud něco nelze přijmout, zkus alespoň přijmout fakt, že to nelze přijmout.',
          'Možná necítíš, že je to správné, možná na to ještě není čas.',
          'Ať už se to týká tebe, tvého těla, osobnosti, zážitků, rozhodnutí, lidí v tvém životě, přání, která máš.',
          'Pokud něco nelze přijmout, nezapomeň, že to může být jen dočasný stav, možná proto, aby ses teď zaměřil/a na něco jiného.',
          'Hlavně nezapomeň, že je to součástí většího a pravděpodobně pozitivnějšího celku.',
          'Pokud tohle přijmeš, vznikne prostor pro pozitivní pocit.',
          'Jasně, možná ten špatný pocit úplně nezmizí a to je v pořádku.',
          'Když ale věci přijmeš, tak jak jsou, máš sílu se s tím vyrovnat.',
        ],
        audio: '',
        obrazek: '',
      },
    },
    {
      id: 10,
      target: 'řešení problému, změna, vlastní aktivita',
      targetId: 'problemsolving',
      nameOfRelaxation:
        'Tipy na změnu nesouvisející s problémem aka Udělej si to hezký',
      keyWords: 'Nic měnit nechci',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Dospěl/a jsi k tomu, že v téhle situaci nic měnit nechceš, ale potřebuješ se prostě jen dostat do pohody? Dochází ti nápady na to jak? Inspiruj se nějakým z tipů.',
          'Dej si něco dobrého. Dobré (ideálně zdravé) jídlo, voňavý čaj, domácí limonádu, kakao.',
          'Udělej si to kolem sebe hezký! Ozdob si část svého pokoje, nástěnku, kus oblečení.',
          'Pusť si příjemnou hudbu. Něco co máš rád/a, nebo naopak vyzkoušej něco nového.',
          'Upusť páru. Jestli cítíš napětí. Bouchni si do polštáře, zakřič si do něj, nebo si pořádně dupni, rozběhni se co nejrychleji.',
          'Tvoř. Maluj, zpívej, tancuj, bubnuj, vymysli báseň. Podle toho, co máš rád/a, a nebo zkus něco nového.',
          'Sportuj. Zkus třeba jógu nebo naopak něco dynamičtějšího. Běh. Na vyplavení endorfinů je dobré třeba skákání přes švihadlo. Zapotíš se i u obyčejných dřepů.',
          'Běž ven. Ať už na klidnou procházku, nebo naopak s cílem vylézt na nejbližší kopec pro získání nadhledu.',
          'Vymysli si vtip, vzpomeň si na originální příhodu, o které jste ještě nemluvili a zavolej/napiš kámošce nebo kámošovi. Nebo někomu, komu už ses dlouho neozval/a.',
          'Viděl jsi naposledy v nějakým videu trik, který ti přišel cool? Nauč se ho. Nauč se trik se svým tělem, s kuchyňským předmětem, s žonglovací pomůckou, kouzlo, origami, novou výtvarnou techniku, ovládni novou appku či technologii (pokud běžně hraješ, zkus se hrám protentokrát vyhnout)',
          'Vytáhni starou hračku. Jasně, už si s nimi nehraješ. Ale není přece jen nějaká, kterou Ti bylo líto vyhodit?',
        ],
        audio: '',
        obrazek: '',
      },
    },
    {
      id: 11,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOfRelaxation: 'Jak poznat, že s námi někdo manipuluje',
      keyWords: 'Řekni NE manipulaci',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Cítíš se v rozhovoru nesvůj/nesvá a nejsi si jistý/á, jestli s tebou někdo komunikuje fér? Nebo jestli ty sám/sama komunikuješ fér?',
          'Manipulace do rovnocenného hovoru nepatří.',
          'Tady je pár základních typů manipulací a rady, jak na ně reagovat.',
          'Lži a polopravdy. Druhý uvádí nepravdivé, zkreslené nebo nepravděpodobné věci, které nelze ověřit.',
          'Co dělat? Neobviňuj ze lhaní. Použij věty: "Těžko věřím, když…", "Já si to pamatuji jinak…".',
          'Odvádění pozornosti. Druhý začne do problému přidávat křivdy, které se staly někdy dříve, nebo jiné osoby.',
          'Co dělat? Nereaguj na to. Vrať se k problému, který řešíte.',
          'Znevažování. Úšklebky, ironie, zesměšňování.',
          'Co dělat? Pomůže samotné uvědomění, že druhý toto dělá, aby se vyhnul řešení.',
          'Nevyčítej. Popiš, že se ti špatně na něčem domlouvá, když to druhý dělá.',
          'Odmítnutí komunikace. Druhý řekne své požadavky a dál se odmítá bavit nebo udělat kompromis.',
          'Co dělat? Požádej o pomoc třetí (nestrannou) osobu. Využij jinou komunikaci - třeba dopis.',
          'Pokud se manipulace v rozhovoru opakuje a cítíš, že na ni nezvládáš reagovat, nemusíš v něm pokračovat. Můžeš ho odložit na dobu, kdy budou emoce menší, nebo požádat další (nestrannou) osobu o pomoc.',
        ],
        audio: '',
      },
    },
    {
      id: 12,
      target: 'První uvolnění',
      targetId: 'stabilization',
      nameOfRelaxation: 'Základní meditace uvolnění',
      keyWords: 'Uvolni mysl',
      typeOfRelaxation: 'Meditace',
      formOfRelaxation: 'Audionahrávka',
      content: {
        text: '',
        audio: 'pozitivni_relaxace.mp3',
      },
    },
  ]);
}
