// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      id: 0,
      target: 'První uvolnění',
      targetId: 'stabilization',
      nameOfRelaxation: 'Základní dechové cvičení pro získání klidu',
      keyWords: 'Dýchej',
      typeOfRelaxation: 'Dechové cvičení',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Lehce se dotkni rtů a trochu pootevři pusu.',
          'Nadechni se nosem a počítej do tří.',
          'Vydechuj a počítej do šesti, zopakuj třikrát.',
          'Teď měj výdech stejně dlouhý jako nádech (třeba nádech na čtyři a výdech na čtyři) a pokračuj tak jednu minutu.',
          'Polož si ruku na břicho a snaž se ho s každým nádechem zvednout.',
        ],
        audio: '',
      },
    },
    {
      id: 1,
      target: 'První uvolnění',
      targetId: 'stabilization',
      nameOFRelaxation: 'Základní progresivní svalová relaxace',
      keyWords: 'Zatni ruce v pěst a uvolni',
      typeOfRelaxation: 'Progresivně svalová relaxace',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Zatni jednu svou ruku v pěst co nejpevněji.',
          'Až bude stisk co nejsilnější, uvolni ho.',
          'Nadechni se a vydechni.',
          'To samé zopakuj s druhou rukou.',
          'Nadechni se a vydechni.',
          'Spolu s uvolněním odchází z těla to nejhorší napětí.',
          'Opakuj dokud se stav nejhoršího napětí nezlepší.',
        ],
        audio: '',
      },
    },
    {
      id: 2,
      target: 'První uvolnění',
      targetId: 'stabilization',
      nameOFRelaxation: 'Tipy na to, jak aktuálně zpomalit',
      keyWords: 'Zpomal svůj pohyb',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Nyní si vyzkoušíš sednout minimálně 10x pomaleji než obvykle',
          'Pokud právě sedíš, stoupni si',
          'Pokud stojíš, najdi si místo, kde si můžeš pohodlně a stabilně sednout, ideálně si opřít záda i ruce',
          'Dojdi k takovému místu na sezení, ale ještě si nesedej',
          'Vytvoř si oporu svých ve svách nohou, postav se tak, jako by ses chystal/a odrazit ke skoku, ale neskákej',
          'Uvědom si že tvé chodidlo stojí na svých palcích, kloubech pod palcem a malíčkem a hranách pat',
          'Pomalu krč nohy až do chvíle, kdy se tvé hýždě dotknou okraje sedadla',
          'Postupně cítíš jak se sedadla dotýká větší a větší část těla',
          'Tvé tělo dosedne a nyní se celé hýždě dotýkají židle',
          'Pokud můžeš stejně pomalu také opři svá záda a ruce',
          'Cítíš, jak tvé tělo těžkne a zanořuje se do sedadla',
          'Uvolni celé tělo, jeho tíhu teď nese věc na které sedíš a dává ti stabilní oporu',
        ],
        audio: '',
      },
    },
    {
      id: 3,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOFRelaxation: 'Jak tu být sám pro sebe',
      keyWords: 'Buď sám pro sebe',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Vzpomeň si, nebo si zkus představit, jaké to je, když tu pro někoho jsi.',
          'Pro blízkého kamaráda, pro mladšího sourozence, pro člověka v nouzi, pro domácí zvíře.',
          'Všímej si svých pocitů, můžeš cítit: zájem, věrnost, obhajování, rozhodnost.',
          'Nyní si vzpomeň, jaké to bylo když jsi byl úplně malé dítě.',
          'Bezbranné, roztomilé.',
          'Zkus nyní vyjádřit ochranu a starost o toto malé dítě.',
          'Zkus sám/sama sebe obejmout tak pevně, jako bys objímal/a toto dítě.',
          'Všímej si jak se cítíš, když jsi na své straně.',
          'Pokud tomuto pocitu něco brání, zkus to pro jednou nechat být.',
          'Nemůže Tě to nyní ohrozit.',
          'Jsi tu jen sám pro sebe.',
          'Nakonec se zeptej sám sebe: Pokud jsem na své straně, co bude nejlepší udělat?',
        ],
        audio: '',
        obraze: '',
      },
    },
    {
      id: 4,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOFRelaxation: 'Arteterapeutický superhrdina (kresba, psaní)',
      keyWords: 'Tvoř svého superhrdinu',
      typeOfRelaxation: 'Arteterapie',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
        'Zkus si vymyslet vlastního superhrdinu, který by tvoje problémy vyřešil levou zadní.',
        'Můžeš o něm psát, nebo ho kreslit.',
        'Dej mu jméno, vymysli, jestli to bude člověk, zvíře, duch, nebo tvor z jiné planety.',
        'Jestli píšeš, popiš, jaké vlastnosti a superschopnosti by měl mít, aby tvůj problém vyřešil.',
        'Pokud kreslíš, zobraz části těla, zbraně nebo jiné nástroje, které by mu pomohly problém vyřešit.',
        ],
        audio: '',
      },
    },
    {
      id: 5,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOFRelaxation: 'Imaginace pro navození pocitu sebelásky a soucitu',
      keyWords: 'Zažij soucit',
      typeOfRelaxation: 'Imaginace a vizualizace',
      formOfRelaxation: 'Audionahrávka',
      content: {
        text: '',
        audio: 'pozitivni_relaxace.mp3',
      },
    },
    {
      id: 6,
      target: 'řešení problému, změna, vlastní aktivita',
      targetId: 'problemsolving',
      nameOFRelaxation: 'Tipy k asertivní a respektující komunikaci',
      keyWords: 'Řešení promluvou',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Bez znalosti situace ti nezvládneme dát konkrétní návod na rozhovor.',
          'Ale můžeme ti doporučit pár obecných pravidel pro komunikaci s druhými:',
          'Pamatuj, že máš úplně stejně práv, názorů, potřeb a snů, jako mají jiní lidé.',
          'Máš právo, aby s tebou lidé zacházeli dobře. I ostatní mají toto právo.',
          'Buď upřímný nejprve k sobě, a pak i k ostatním.',
          'Na rozhovor se připrav a pokus si stanovit, co bys potřeboval/a.',
          'Nehodnoť druhé. Popiš co nejkonkrétněji, co Ti vadí.',
          'Nabídni řešení, která tě napadají a vyslechni si řešení druhé strany.',
          'Možná budeš muset udělat kompromis.',
          'Vzniklá dohoda musí být přijatelná pro obě strany, jinak se nejedná o dohodu.',
          'Nemusíš pokračovat v rozhovoru s rozlobeným člověkem, můžeš ho odložit.',
          'Manipulace do respektujícího rozhovoru nepatří, nauč se ji rozeznat.',
          'Neboj se požádat o pomoc.',
        ],
        audio: '',
      },
    },
    {
      id: 7,
      target: 'řešení problému, změna, vlastní aktivita',
      targetId: 'problemsolving',
      nameOFRelaxation: 'Jak se někomu svěřit',
      keyWords: 'Svěř se',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Nikdy nemusíš být na nic sám.',
          'Nejlepší je svěřit se někomu ve chvíli, kdy cítíš, že problém sám nezvládneš.',
          'Nejedná se o žalování, pokud jsi sám v situaci bezradný.',
          'Mohou ti pomoci rodiče, jiný blízký příbuzný, kamarád, učitel, školní psycholog, jiný zaměstnanec školy, vedoucí v kroužku, trenér.',
          'Někdy se může zdát, že pomoc někoho známého nepomohla, neboj se to zkusit u někoho jiného.',
          'Existuje také pomoc zvenčí. Jsou jimi různé instituce jako například centrum Locika či Linka bezpečí.',
        ],
        audio: '',
      },
    },
    {
      id: 8,
      target: 'řešení problému, změna, vlastní aktivita',
      targetId: 'problemsolving',
      nameOFRelaxation: 'Co dělat, když nevidím řešení',
      keyWords: 'Tohle řešit nejde',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Být tu sám pro sebe znamená, že ti na sobě záleží.',
          'Znamená to, že chceš být šťastná/ý, ne ustaraná/ý, smutná/ý, naštvaná/ý, nebo provinilá/ý.',
          'To jak se teď cítíš je pro tebe důležité nejen v tuto chvíli, ale i pro tvé budoucí já, které bude čerpat i z této zkušenosti.',
          'Pokud jsi došel/došla až sem, udělal/a jsi pro sebe zásadní krok.',
          'Znamená to, že jsi získal/a odvahu a rozhodl/a ses pro řešení své situace a to i v případě, že ho nyní nevidíš.',
          'Můžeš vyzkoušet i jiná cvičení z MindSprout.',
          'Nebo daná situace může vyžadovat více času než jedno rychlé řešení.',
          'Pokud cítíš, že Ti s problémem MindSprout nepomůže, můžeš vyzkoušet nějaký z následujících odkazů na konci stránky.',
        ],
        audio: '',
      },
    },
    {
      id: 9,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOFRelaxation: 'Imaginace pro vytvoření si důvěrníka',
      keyWords: 'Buď sobě nejlepším přítelem',
      typeOfRelaxation: 'Imaginace a vizualizace',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Představ si někoho, kdo ti je blízký a komu na tobě záleží.',
          'Může to být kamarád, rodič, sourozenec, domácí mazlíček nebo dokonce imaginární přítel.',
          'Zaměř se na ten pocit, že jsi pro tu osobu důležitý/á.',
          'Teď si vzpomeň na něco, co tě trápí, a pokus si představit, že s tebou tato bytost soucítí.',
          'Vzpomeň si na její gesta, výraz obličeje, a jaký postoj k tobě má.',
          'Pokus se tento soucit přijmout.',
          'Někdo ti rozumí a stará se o tebe.',
          'Cítíš větší klid a můžeš volněji vydechnout.',
        ],
        audio: '',
        obrazek: '',
      },
    },
    {
      id: 10,
      target: 'řešení problému, změna, vlastní aktivita',
      targetId: 'problemsolving',
      nameOFRelaxation:
        'Tipy na změnu nesouvisející s problémem aka Udělej si to hezký',
      keyWords: 'Nic měnit nechci',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Dospěl jsi k tomu, že v téhle situaci nic měnit nechceš, ale potřebuješ se prostě jen dostat do pohody? Dochází ti nápady na to jak? Inspiruj se.',
          'Dej si něco dobrého. Zdravé jídlo, voňavý čaj, domácí limonádu, kakao.',
          'Udělej si to kolem sebe hezký! Ozdob si část svého pokoje, nástěnku, kus oblečení.',
          'Pusť si příjemnou hudbu. Něco co máš rád/a, nebo naopak vyzkoušej něco nového.',
          'Upusť páru. Jestli cítíš napětí. Bouchni si do polštáře, zakřič si do něj, nebo si pořádně dupni, rozběhni se co nejrychleji.',
          'Tvoř. Maluj, zpívej, tancuj, bubnuj, vymysli báseň. Podle toho, co máš rád, a nebo zkus něco nového.',
          'Sportuj. Zkus třeba jógu nebo naopak něco dynamičtějšího. Běh. Na vyplavení endorfinů je dobré třeba skákání přes švihadlo. Zapotíš se třeba u obyčejných dřepů.',
          'Vyraž ven. Ať už na klidnou procházku, nebo naopak s cílem vylézt na nejbližší kopec pro získání nadhledu.',
          'Vymysli si vtip, vzpomeň si na originální příhodu, o které jste ještě nemluvili a zavolej/napiš kamarádovi/kamarádce. Nebo někomu komu už ses dlouho neozval/a.',
          'Nauč se nový trik. Se svým tělem, s kuchyňským předmětem, s žonglovací pomůckou. Origami. Videí a návodů je plný internet.',
          'Vytáhni starou hračku. Jasně, už si s nimi nehraješ. Ale není přece jen nějaká, kterou Ti bylo líto vyhodit?',
        ],
        audio: '',
        obrazek: '',
      },
    },
    {
      id: 11,
      target: 'vnímání pocitů, problémů a sám sebe',
      targetId: 'selfperception',
      nameOFRelaxation: 'Jak poznat, že s námi někdo manipuluje',
      keyWords: 'Řekni NE manipulaci',
      typeOfRelaxation: 'Tipy na aktivity',
      formOfRelaxation: 'Psaný text',
      content: {
        text: [
          'Cítíš se v rozhovoru nesvůj/nesvá a nejsi si jistý/á, zda s tebou někdo jiný komunikuje fér? Nebo zda ty sám/sama komunikuješ fér? Manipulace do rovnocenného hovoru nepatří. Tady je pár základních typů manipulací a rady, jak na ně reagovat.',
          "Lži a polopravdy. Druhý uvádí nepravdivé, zkreslené nebo nepravděpodobné věci, které nelze ověřit. Co dělat? Neobviňuj ze lhaní. Použij věty: 'Těžko věřím když…', 'Já si to pamatuji jinak…'.",
          'Odvádění pozornosti. Druhý začne do problému přidávat křivdy, které se staly někdy dříve, nebo jiné osoby. Co dělat? Nereaguj na to. Vrať se k problému, který řešíte.',
          'Znevažování. Úšklebky, ironie, zesměšňování. Co dělat? Pomůže samotné uvědomění, že druhý toto dělá, aby se vyhnul řešení. Nevyčítej. Popiš, že se Ti špatně na něčem domlouvá, když to druhý dělá.',
          'Odmítnutí komunikace. Druhý řekne své požadavky a dál se odmítá bavit nebo udělat kompromis. Co dělat? Požádej o pomoc třetí (nestrannou) osobu. Využij jiné komunikace - např. dopis.',
          'Pokud se manipulace v rozhovoru opakuje a cítíš, že na ni nezvládáš reagovat, nemusíš v něm pokračovat. Můžeš ho například odložit na dobu, kdy budou emoce menší, nebo požádat další (nestrannou) osobu o pomoc.',
        ],
        audio: '',
      },
    },
    {
      id: 12,
      target: 'První uvolnění',
      targetId: 'stabilization',
      nameOFRelaxation: 'Základní meditace uvolnění',
      keyWords: 'Uvolni mysl',
      typeOfRelaxation: 'Meditace',
      formOfRelaxation: 'Audionahrávka',
      content: {
        text: '',
        audio: 'pozitivni_relaxace.mp3',
      },
    },
  ]);
}
